# Generated by Django 3.0.7 on 2020-06-17 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoqueitens',
            options={},
        ),
    ]
